
[functions.anaf_lookup]
enabled = true
verify_jwt = true
import_map = "./functions/anaf_lookup/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/anaf_lookup/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/anaf_lookup/*.html" ]

[functions.anaf-lookup]
enabled = true
verify_jwt = true
import_map = "./functions/anaf-lookup/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/anaf-lookup/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/anaf-lookup/*.html" ]
